
package com.zenith;
enum TokenType {
    //SINGLE CHARACTER TOKEN
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA,MINUS, PLUS, SLASH, SEMICOLON, STAR,PERCENT,

    //ONE OR TWO CHARACTER TOKEN
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    ARROW, PLUS_PLUS, MINUS_MINUS,

    //LITERALS
    IDENTIFIER,STRING,INTEGER,FLOAT,

    //KEYWORDS
    AND, ELSE, FALSE, FN, FOR, IF, NIL, OR, 
    TRUE, RETURN, WHILE, INT, FLOAT_TYPE, STRING_TYPE, BOOL, WRITELN,

    //SPECIAL
    EOF// end of file


}
